
#pragma once

#ifndef SQLITE3_CONFIGURE_H_
#define SQLITE3_CONFIGURE_H_

#define SQLITE_ENABLE_RTREE
#define SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_HAS_CODEC 1
#define SQLITE3ENCRYPT_EXPORTS
#define SQLITE_ENABLE_FTS3
#define SQLITE_ENABLE_FTS3_PARENTHESIS
#define SQLITE_SECURE_DELETE
#define SQLITE_SOUNDEX
#define CODEC_TYPE CODEC_TYPE_AES128


#endif